# Generated by Django 6.0.7 on 2026-08-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-created_at',), 'permissions': [('confirm_purchase', 'Can confirm purchase')]},
        ),
    ]
