# Generated by Django 6.0.7 on 2026-08-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-created_at',), 'permissions': [('confirm_purchase', 'Can confirm purchase'), ('cancel_purchase', 'Can cancel purchase')]},
        ),
    ]
