# Generated by Django 6.0.7 on 2026-08-26 22:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__lt', Decimal('0')), _negated=True), name='coupon_discount_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage'), ('discount_value__lte', Decimal('100'))), models.Q(('discount_type', 'percentage'), _negated=True), _connector='OR'), name='coupon_discount_percentage_max_100'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_invoice_amount__isnull', True), models.Q(('minimum_invoice_amount__lt', Decimal('0')), _negated=True), _connector='OR'), name='coupon_minimum_invoice_amount_non_negative'),
        ),
    ]
