# Generated by Django 6.0.7 on 2026-08-26 22:51

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_coupon_discount_value_non_negative_and_more'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('products', '0002_cartonpricing_cartonpricing_carton_price_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('coupon_discount__gte', Decimal('0'))), name='invoice_coupon_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='invoice_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0'))), name='invoice_item_unit_price_non_negative'),
        ),
    ]
