# Generated by Django 6.0.7 on 2026-08-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoice_coupon_discount_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], db_index=True, default='draft', max_length=20),
        ),
    ]
