# Generated by Django 6.0.8 on 2026-08-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',), 'permissions': [('confirm_invoice', 'Can confirm an invoice'), ('cancel_invoice', 'Can cancel an invoice'), ('apply_invoice_coupon', 'Can apply a coupon to an invoice')]},
        ),
    ]
