# Generated by Django 4.2.30 on 2026-07-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiondevice',
            name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
        migrations.DeleteModel(
            name='SessionDevice',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
