# Generated by Django 4.2.30 on 2026-07-20 00:53

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_sessiondevice_session_remove_usersession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.CheckConstraint(condition=models.Q(('username__contains', '@'), _negated=True), name='accounts_user_username_not_at'),
        ),
        migrations.AddConstraint(
            model_name='customusermodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
    ]
