# Generated by Django 6.0.7 on 2026-07-23 21:09

import accounts.managers.user_manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_move_authsession_state"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customusermodel",
            managers=[
                ("objects", accounts.managers.user_manager.CustomUserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="customusermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", ""), _negated=True),
                name="accounts_user_email_not_empty",
            ),
        ),
    ]
