# Generated by Django 6.0.7 on 2026-07-26

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_customusermodel_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "Sign up"),
                            ("email_change", "Email change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_email_verification_request",
            },
        ),
        migrations.AddConstraint(
            model_name="emailverificationrequest",
            constraint=models.UniqueConstraint(
                fields=("user", "purpose"),
                name="email_verification_one_per_user_purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="emailverificationrequest",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("purpose", "email_change")),
                name="email_change_pending_email_ci_unique",
            ),
        ),
    ]
