# Generated by Django 6.0.7 on 2026-08-27 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_stockmovementitem'),
        ('products', '0002_cartonpricing_cartonpricing_carton_price_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.stocklocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'product'], name='stock_bal_loc_prod_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'product'), name='stock_balance_unique_location_product')],
            },
        ),
    ]
