# Generated by Django 6.0.7 on 2026-08-27 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('location_type', 'MAIN_WAREHOUSE')), fields=('location_type',), name='inventory_one_active_main_warehouse'),
        ),
    ]
