# Generated by Django 6.0.7 on 2026-07-27 22:06

import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('site_type', models.CharField(choices=[('head_office', 'Head office'), ('branch', 'Branch'), ('store', 'Store')], max_length=20)),
                ('address_line_1', models.CharField(max_length=250)),
                ('address_line_2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state_or_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='organization.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.site')),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('company'), name='organization_site_company_code_ci_unique'), models.UniqueConstraint(condition=models.Q(('site_type', 'head_office')), fields=('company',), name='organization_one_head_office_per_company'), models.CheckConstraint(condition=models.Q(('site_type', 'store'), ('parent__isnull', True), _connector='OR'), name='organization_only_store_may_have_parent')],
            },
        ),
    ]
