# Generated by Django 6.0.7 on 2026-07-28 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='country_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Enter a valid two-letter country code.', regex='^[A-Za-z]{2}$')]),
        ),
    ]
