# Generated by Django 6.0.7 on 2026-08-26 22:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoice_coupon_discount_non_negative_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0'))), name='payment_amount_non_negative'),
        ),
    ]
