# Generated by Django 6.0.7 on 2026-08-27 00:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoices', '0003_invoice_status'),
        ('payments', '0002_payment_payment_amount_non_negative'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_invoice_status_idx',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_amount_non_negative',
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.paymenttransaction'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gte', Decimal('0'))), name='payment_tx_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_amount__gte', Decimal('0'))), name='payment_tx_transfer_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('transaction', 'invoice'), name='payment_alloc_unique_tx_invoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gte', Decimal('0'))), name='payment_alloc_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_amount__gte', Decimal('0'))), name='payment_alloc_transfer_non_negative'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
