# Generated by Django 6.0.8 on 2026-08-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentallocation_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ('-created_at',), 'permissions': [('process_collection', 'Can process a payment collection')]},
        ),
    ]
