# Generated by Django 6.0.8 on 2026-08-31 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymenttransaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('path', models.CharField(help_text='Normalized request path.', max_length=500)),
                ('request_signature', models.CharField(help_text='SHA-256 of the canonical request body.', max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'path', 'key'], name='idempotency_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'user', 'path'), name='idempotency_unique_key_user_path')],
            },
        ),
    ]
