# Generated by Django 6.0.8 on 2026-08-31 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0005_idempotencykey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='collected_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who performed the collection.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['customer', 'created_at'], name='pay_tx_cust_created_idx'),
        ),
    ]
