import 'package:flutter/material.dart';

/// بيانات تقرير اليوم لعرضه/مشاركته كصورة.
class DailyReportData {
  final DateTime date;
  final int invoices;
  final int customers;
  final int products;
  final double invoiceValue;
  final double outstanding;
  final double cashReceived;
  final double transfersReceived;

  const DailyReportData({
    required this.date,
    required this.invoices,
    required this.customers,
    required this.products,
    required this.invoiceValue,
    required this.outstanding,
    required this.cashReceived,
    required this.transfersReceived,
  });
}

/// كارت تقرير اليوم — يرسم نضيفًا ويُشارك كصورة.
class DailyReportCard extends StatelessWidget {
  final DailyReportData data;
  final double width;

  const DailyReportCard({
    super.key,
    required this.data,
    this.width = 360,
  });

  String _money(double v) => '${v.toStringAsFixed(2)} EGP';

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final dateText =
        '${data.date.day.toString().padLeft(2, '0')}/${data.date.month.toString().padLeft(2, '0')}/${data.date.year}';

    return Container(
      width: width,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [scheme.primaryContainer.withValues(alpha: .6), scheme.surface],
        ),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: scheme.outlineVariant.withValues(alpha: .5)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            Icon(Icons.today_outlined, color: scheme.primary, size: 22),
            const SizedBox(width: 8),
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Daily Business Report',
                    style: TextStyle(fontWeight: FontWeight.w800, fontSize: 17)),
                Text('Sales ERP — $dateText',
                    style: TextStyle(fontSize: 12, color: scheme.onSurfaceVariant)),
              ],
            ),
          ]),
          const SizedBox(height: 16),
          const Divider(thickness: 1),
          const SizedBox(height: 12),
          _metric('Invoices issued', '${data.invoices}', Icons.receipt_long, scheme),
          _metric('Customers', '${data.customers}', Icons.people_outline, scheme),
          _metric('Products', '${data.products}', Icons.inventory_2_outlined, scheme),
          const SizedBox(height: 12),
          const Divider(thickness: 1),
          const SizedBox(height: 12),
          Text('Financial overview',
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: scheme.onSurfaceVariant)),
          const SizedBox(height: 8),
          _moneyRow('Invoice value', data.invoiceValue, scheme),
          _moneyRow('Cash received', data.cashReceived, scheme),
          _moneyRow('Transfers', data.transfersReceived, scheme),
          _moneyRow('Outstanding', data.outstanding, scheme, emphasized: true),
          const SizedBox(height: 14),
          Center(
            child: Text('Generated by Sales ERP',
                style: TextStyle(fontSize: 11, color: scheme.onSurfaceVariant)),
          ),
        ],
      ),
    );
  }

  Widget _metric(String label, String value, IconData icon, ColorScheme scheme) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 5),
      child: Row(children: [
        Icon(icon, size: 18, color: scheme.primary),
        const SizedBox(width: 10),
        Expanded(child: Text(label, style: TextStyle(fontSize: 14))),
        Text(value, style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700)),
      ]),
    );
  }

  Widget _moneyRow(String label, double amount, ColorScheme scheme,
      {bool emphasized = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label,
              style: TextStyle(
                  fontSize: emphasized ? 14 : 13,
                  fontWeight: emphasized ? FontWeight.w700 : FontWeight.w500)),
          Text(_money(amount),
              style: TextStyle(
                  fontSize: emphasized ? 15 : 13,
                  fontWeight: emphasized ? FontWeight.w800 : FontWeight.w600,
                  color: emphasized ? scheme.primary : scheme.onSurface)),
        ],
      ),
    );
  }
}