# Generated by Django 6.0.7 on 2026-08-26 22:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartonpricing',
            constraint=models.CheckConstraint(condition=models.Q(('carton_price__gte', Decimal('0'))), name='cartonpricing_carton_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0'))), name='product_price_non_negative'),
        ),
    ]
