# Generated by Django 6.0.7 on 2026-08-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartonpricing_cartonpricing_carton_price_non_negative_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_price_non_negative',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='product_purchase_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='product_selling_price_non_negative'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
